name: Build & Release Plugin

on:
  push:
    tags:
      - "v*" # Runs only when you push a version tag like v1.0.0

permissions:
  contents: write # ✅ Required for creating releases with GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up PHP (so Composer works properly)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1" # Match your plugin's minimum PHP version
          tools: composer

      # 3. Install composer dependencies (required for PUC autoloader)
      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      # 4. Prepare build folder (copy plugin files except excluded ones)
      - name: Prepare build
        run: |
          mkdir -p build/vms-plugin
          rsync -av ./ build/vms-plugin/ \
            --exclude build \
            --exclude .git \
            --exclude .github \
            --exclude composer.json \
            --exclude composer.lock \
            --exclude node_modules \
            --exclude tests

      # 5. Create plugin zip
      - name: Build plugin zip
        run: |
          cd build
          zip -r vms-plugin.zip vms-plugin

      # 6. Create GitHub Release and upload the built ZIP
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/vms-plugin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
